import type { CanvasObject, StrokePattern } from "./canvas-types";

export type DiagramTemplate = {
  id: string;
  title: string;
  category: string;
  description: string;
  sourceName: "TikZ.net" | "Janosh Diagrams" | "Sketch2LaTeX";
  sourceUrl: string;
  license: string;
  objects: CanvasObject[];
};

const o = (id: string, object: Omit<CanvasObject, "id">): CanvasObject => ({ id, ...object });
const concours = (strokeWidth = 2, strokePattern: StrokePattern = "solid") => ({ stroke: "#111111", strokeWidth, strokePattern });

export const diagramTemplates: DiagramTemplate[] = [
  {
    id: "rlc-series",
    title: "Circuit RLC série",
    category: "Électricité",
    description: "Générateur, résistance, bobine et condensateur en boucle, prêts à annoter.",
    sourceName: "TikZ.net",
    sourceUrl: "https://tikz.net/rlc-circuit/",
    license: "Adapté sous CC BY-SA 4.0",
    objects: [
      o("rlc-battery", { kind: "battery", x: 120, y: 390, x2: 120, y2: 160 }),
      o("rlc-top", { kind: "wire", x: 120, y: 160, x2: 270, y2: 160 }),
      o("rlc-r", { kind: "resistor", x: 270, y: 160, x2: 430, y2: 160, annotations: { main: "R" } }),
      o("rlc-l", { kind: "inductor", x: 430, y: 160, x2: 590, y2: 160, annotations: { main: "L" } }),
      o("rlc-right", { kind: "wire", x: 590, y: 160, x2: 590, y2: 390 }),
      o("rlc-c", { kind: "capacitor", x: 590, y: 390, x2: 430, y2: 390, annotations: { main: "C" } }),
      o("rlc-bottom", { kind: "wire", x: 430, y: 390, x2: 120, y2: 390 }),
      o("rlc-i", { kind: "arrow", x: 190, y: 130, x2: 340, y2: 130, annotations: { main: "i(t)" }, style: concours() }),
      o("rlc-title", { kind: "text", x: 355, y: 90, text: "Circuit RLC série" }),
    ],
  },
  {
    id: "thevenin-equivalent",
    title: "Équivalent de Thévenin",
    category: "Électricité",
    description: "Générateur idéal de tension ETh et résistance RTh en série, avec bornes de sortie A et B.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://tug.ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf",
    license: "Création originale – conventions européennes CircuitikZ",
    objects: [
      o("th-source", { kind: "voltage-source", x: 180, y: 360, x2: 180, y2: 180, annotations: { main: "E_{Th}" } }),
      o("th-top-left", { kind: "wire", x: 180, y: 180, x2: 300, y2: 180 }),
      o("th-resistor", { kind: "resistor", x: 300, y: 180, x2: 480, y2: 180, annotations: { main: "R_{Th}" } }),
      o("th-top-right", { kind: "wire", x: 480, y: 180, x2: 650, y2: 180 }),
      o("th-bottom", { kind: "wire", x: 180, y: 360, x2: 650, y2: 360 }),
      o("th-terminal-a", { kind: "circle", x: 644, y: 174, width: 12, height: 12 }),
      o("th-terminal-b", { kind: "circle", x: 644, y: 354, width: 12, height: 12 }),
      o("th-label-a", { kind: "text", x: 670, y: 185, text: "A" }),
      o("th-label-b", { kind: "text", x: 670, y: 365, text: "B" }),
      o("th-title", { kind: "text", x: 340, y: 105, text: "Modèle de Thévenin" }),
    ],
  },
  {
    id: "norton-equivalent",
    title: "Équivalent de Norton",
    category: "Électricité",
    description: "Générateur idéal de courant IN et résistance RN en parallèle, avec bornes de sortie A et B.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://tug.ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf",
    license: "Création originale – conventions européennes CircuitikZ",
    objects: [
      o("no-source", { kind: "current-source", x: 250, y: 360, x2: 250, y2: 180, annotations: { main: "I_N" } }),
      o("no-top-left", { kind: "wire", x: 250, y: 180, x2: 450, y2: 180 }),
      o("no-top-right", { kind: "wire", x: 450, y: 180, x2: 650, y2: 180 }),
      o("no-resistor", { kind: "resistor", x: 450, y: 180, x2: 450, y2: 360, annotations: { main: "R_N" } }),
      o("no-bottom-left", { kind: "wire", x: 250, y: 360, x2: 450, y2: 360 }),
      o("no-bottom-right", { kind: "wire", x: 450, y: 360, x2: 650, y2: 360 }),
      o("no-terminal-a", { kind: "circle", x: 644, y: 174, width: 12, height: 12 }),
      o("no-terminal-b", { kind: "circle", x: 644, y: 354, width: 12, height: 12 }),
      o("no-label-a", { kind: "text", x: 670, y: 185, text: "A" }),
      o("no-label-b", { kind: "text", x: 670, y: 365, text: "B" }),
      o("no-title", { kind: "text", x: 350, y: 105, text: "Modèle de Norton" }),
    ],
  },
  {
    id: "ideal-transformer",
    title: "Transformateur idéal",
    category: "Électricité",
    description: "Transformateur européen à noyau, primaire N1, secondaire N2 et charge résistive.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://tug.ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf",
    license: "Création originale – conventions européennes CircuitikZ",
    objects: [
      o("tr-source", { kind: "voltage-source", x: 150, y: 290, x2: 150, y2: 210, annotations: { main: "u_1" } }),
      o("tr-primary-top", { kind: "wire", x: 150, y: 210, x2: 340, y2: 210, bindings: { endId: "tr-core", endPort: "primary-top" } }),
      o("tr-primary-bottom", { kind: "wire", x: 150, y: 290, x2: 340, y2: 290, bindings: { endId: "tr-core", endPort: "primary-bottom" } }),
      o("tr-core", { kind: "transformer", x: 340, y: 170, width: 140, height: 160, annotations: { primary: "N_1", secondary: "N_2" } }),
      o("tr-secondary-top", { kind: "wire", x: 480, y: 210, x2: 650, y2: 210, bindings: { startId: "tr-core", startPort: "secondary-top" } }),
      o("tr-load", { kind: "resistor", x: 650, y: 210, x2: 650, y2: 290, annotations: { main: "R" } }),
      o("tr-secondary-bottom", { kind: "wire", x: 650, y: 290, x2: 480, y2: 290, bindings: { endId: "tr-core", endPort: "secondary-bottom" } }),
      o("tr-current-primary", { kind: "arrow", x: 210, y: 190, x2: 300, y2: 190, annotations: { main: "i_1" }, style: concours() }),
      o("tr-current-secondary", { kind: "arrow", x: 520, y: 190, x2: 610, y2: 190, annotations: { main: "i_2" }, style: concours() }),
      o("tr-title", { kind: "text", x: 345, y: 105, text: "Transformateur idéal en charge" }),
    ],
  },
  {
    id: "closed-loop-control",
    title: "Asservissement en boucle fermée",
    category: "Automatique",
    description: "Comparateur, correcteur C(p), procédé H(p), chaîne de mesure et retour négatif.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://eduscol.education.gouv.fr/sites/default/files/document/cglscin-2024pdf-105519.pdf",
    license: "Création originale – conventions des schémas-blocs de concours français",
    objects: [
      o("fb-input", { kind: "signal-arrow", x: 70, y: 250, x2: 180, y2: 250, annotations: { main: "E(p)" }, bindings: { endId: "fb-sum", endPort: "input-left" }, style: concours() }),
      o("fb-sum", { kind: "summing-junction", x: 180, y: 215, width: 70, height: 70, annotations: { left: "+", top: "", bottom: "−" } }),
      o("fb-error", { kind: "signal-arrow", x: 250, y: 250, x2: 330, y2: 250, annotations: { main: "ε(p)" }, bindings: { startId: "fb-sum", startPort: "output", endId: "fb-corrector", endPort: "input" }, style: concours() }),
      o("fb-corrector", { kind: "transfer-block", x: 330, y: 215, width: 120, height: 70, annotations: { main: "C(p)" } }),
      o("fb-command", { kind: "signal-arrow", x: 450, y: 250, x2: 540, y2: 250, annotations: { main: "U(p)" }, bindings: { startId: "fb-corrector", startPort: "output", endId: "fb-process", endPort: "input" }, style: concours() }),
      o("fb-process", { kind: "transfer-block", x: 540, y: 215, width: 120, height: 70, annotations: { main: "H(p)" } }),
      o("fb-forward", { kind: "signal-arrow", x: 660, y: 250, x2: 720, y2: 250, annotations: { main: "" }, bindings: { startId: "fb-process", startPort: "output", endId: "fb-takeoff", endPort: "branch" }, style: concours() }),
      o("fb-takeoff", { kind: "takeoff-point", x: 711, y: 241, width: 18, height: 18 }),
      o("fb-output", { kind: "signal-arrow", x: 720, y: 250, x2: 830, y2: 250, annotations: { main: "S(p)" }, bindings: { startId: "fb-takeoff", startPort: "branch" }, style: concours() }),
      o("fb-down", { kind: "line", x: 720, y: 250, x2: 720, y2: 420, bindings: { startId: "fb-takeoff", startPort: "branch" }, style: concours() }),
      o("fb-measure-in", { kind: "signal-arrow", x: 720, y: 420, x2: 600, y2: 420, annotations: { main: "" }, bindings: { endId: "fb-measure", endPort: "input" }, style: concours() }),
      o("fb-measure", { kind: "transfer-block", x: 480, y: 385, width: 120, height: 70, annotations: { main: "H_m(p)" } }),
      o("fb-return-horizontal", { kind: "line", x: 480, y: 420, x2: 215, y2: 420, bindings: { startId: "fb-measure", startPort: "output" }, style: concours() }),
      o("fb-return-up", { kind: "signal-arrow", x: 215, y: 420, x2: 215, y2: 285, annotations: { main: "" }, bindings: { endId: "fb-sum", endPort: "input-bottom" }, style: concours() }),
      o("fb-title", { kind: "text", x: 330, y: 105, text: "Asservissement à retour négatif" }),
    ],
  },
  {
    id: "first-order-identification-performance",
    title: "Identification d’un premier ordre — performances",
    category: "Automatique",
    description: "Planche concours reliant réponse indicielle, bande à ±5 %, temps de réponse, diagrammes de Bode réel et asymptotique, pulsation de cassure et pôle réel.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/textes/cpge/cpge-mathematiques-physique-sciences-de-lingenieur-mpsi-mp/mp-cycle-complet-2021/18309-mpsi-et-mp-sciences-industrielles-de-lingenieur-2021.pdf",
    license: "Original creation — STEM control-systems conventions",
    objects: [
      o("fo-time-frame", { kind: "time-response-diagram", x: 25, y: 50, width: 420, height: 240, annotations: { title: "Réponse indicielle — premier ordre", input: "échelon", signal: "s(t)", unit: "s", timeMin: "0", timeMax: "10", yMin: "0", yMax: "1.5" } }),
      o("fo-time-trace", { kind: "time-response-trace", x: 25, y: 50, width: 420, height: 240, annotations: { model: "premier ordre", input: "échelon", gain: "1", tau: "1", omega0: "1", damping: "1", main: "s(t)" }, style: concours(2.2) }),
      o("fo-settling-band", { kind: "settling-band", x: 25, y: 50, width: 420, height: 240, annotations: { target: "1", tolerance: "5", main: "±5 %" }, style: concours(1.2, "dashed") }),
      o("fo-t5-marker", { kind: "performance-marker", x: 185, y: 84, x2: 185, y2: 258, annotations: { performanceType: "t5%", main: "t_5% ≃ 3τ" }, style: concours(1.2, "dashed") }),

      o("fo-bode-frame", { kind: "bode-diagram", x: 475, y: 40, width: 420, height: 300, annotations: { title: "Premier ordre — Bode", transferFunction: "H(p)=K/(1+τp)", omegaMin: "0.1", omegaMax: "1000", gainMin: "-60", gainMax: "40", phaseMin: "-180", phaseMax: "0", frequencyUnit: "rad/s" } }),
      o("fo-bode-module-real", { kind: "bode-trace", x: 475, y: 40, width: 420, height: 300, annotations: { channel: "module", traceType: "réel", model: "premier ordre", gain: "1", omega0: "10", damping: "1", main: "H" }, style: concours(2.2) }),
      o("fo-bode-phase-real", { kind: "bode-trace", x: 475, y: 40, width: 420, height: 300, annotations: { channel: "phase", traceType: "réel", model: "premier ordre", gain: "1", omega0: "10", damping: "1", main: "H" }, style: concours(2.2) }),
      o("fo-bode-module-asymptote", { kind: "bode-trace", x: 475, y: 40, width: 420, height: 300, annotations: { channel: "module", traceType: "asymptotique", model: "premier ordre", gain: "1", omega0: "10", damping: "1", main: "" }, style: concours(1.2, "dashed") }),
      o("fo-bode-phase-asymptote", { kind: "bode-trace", x: 475, y: 40, width: 420, height: 300, annotations: { channel: "phase", traceType: "asymptotique", model: "premier ordre", gain: "1", omega0: "10", damping: "1", main: "" }, style: concours(1.2, "dashed") }),
      o("fo-bode-break", { kind: "bode-break", x: 707, y: 74, x2: 707, y2: 312, annotations: { main: "ω_0=1/τ" }, style: concours(1.2, "dashed") }),
      o("fo-bode-slope", { kind: "bode-slope", x: 707, y: 118, x2: 794, y2: 162, annotations: { main: "-20 dB/décade", slope: "-20" }, style: concours(1.5) }),
      o("fo-pole-map", { kind: "pole-zero-map", x: 525, y: 365, width: 320, height: 260, annotations: { main: "Premier ordre — plan complexe", poles: "-1", zeros: "", realMin: "-4", realMax: "1", imagMin: "-2", imagMax: "2" } }),
    ],
  },
  {
    id: "second-order-underdamped-performance",
    title: "Deuxième ordre sous-amorti — dépassement et rapidité",
    category: "Automatique",
    description: "Planche concours d’un deuxième ordre pseudo-périodique avec premier dépassement D1, temps de réponse à 5 %, résonance de Bode et pôles complexes conjugués.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/18275/18275-sciences-industrielles-2025-doc-reponse.pdf",
    license: "Original creation — STEM control-systems conventions",
    objects: [
      o("so-time-frame", { kind: "time-response-diagram", x: 25, y: 40, width: 420, height: 240, annotations: { title: "Réponse indicielle — deuxième ordre", input: "échelon", signal: "s(t)", unit: "s", timeMin: "0", timeMax: "10", yMin: "0", yMax: "1.5" } }),
      o("so-time-trace", { kind: "time-response-trace", x: 25, y: 40, width: 420, height: 240, annotations: { model: "deuxième ordre", input: "échelon", gain: "1", tau: "1", omega0: "2", damping: "0.35", main: "s(t)" }, style: concours(2.2) }),
      o("so-settling-band", { kind: "settling-band", x: 25, y: 40, width: 420, height: 240, annotations: { target: "1", tolerance: "5", main: "±5 %" }, style: concours(1.2, "dashed") }),
      o("so-d1-marker", { kind: "performance-marker", x: 140, y: 96, x2: 140, y2: 132, annotations: { performanceType: "D1%", main: "D_1" }, style: concours(1.2, "dashed") }),
      o("so-t5-marker", { kind: "performance-marker", x: 230, y: 74, x2: 230, y2: 248, annotations: { performanceType: "t5%", main: "t_5%" }, style: concours(1.2, "dashed") }),

      o("so-bode-frame", { kind: "bode-diagram", x: 475, y: 30, width: 420, height: 300, annotations: { title: "Deuxième ordre sous-amorti — Bode", transferFunction: "H(p)", omegaMin: "0.1", omegaMax: "1000", gainMin: "-60", gainMax: "40", phaseMin: "-180", phaseMax: "0", frequencyUnit: "rad/s" } }),
      o("so-bode-module-real", { kind: "bode-trace", x: 475, y: 30, width: 420, height: 300, annotations: { channel: "module", traceType: "réel", model: "deuxième ordre", gain: "1", omega0: "2", damping: "0.35", main: "H" }, style: concours(2.2) }),
      o("so-bode-phase-real", { kind: "bode-trace", x: 475, y: 30, width: 420, height: 300, annotations: { channel: "phase", traceType: "réel", model: "deuxième ordre", gain: "1", omega0: "2", damping: "0.35", main: "H" }, style: concours(2.2) }),
      o("so-bode-module-asymptote", { kind: "bode-trace", x: 475, y: 30, width: 420, height: 300, annotations: { channel: "module", traceType: "asymptotique", model: "deuxième ordre", gain: "1", omega0: "2", damping: "0.35", main: "" }, style: concours(1.2, "dashed") }),
      o("so-bode-phase-asymptote", { kind: "bode-trace", x: 475, y: 30, width: 420, height: 300, annotations: { channel: "phase", traceType: "asymptotique", model: "deuxième ordre", gain: "1", omega0: "2", damping: "0.35", main: "" }, style: concours(1.2, "dashed") }),
      o("so-bode-break", { kind: "bode-break", x: 646, y: 64, x2: 646, y2: 302, annotations: { main: "ω_0" }, style: concours(1.2, "dashed") }),
      o("so-bode-slope", { kind: "bode-slope", x: 646, y: 126, x2: 733, y2: 214, annotations: { main: "-40 dB/décade", slope: "-40" }, style: concours(1.5) }),
      o("so-pole-map", { kind: "pole-zero-map", x: 525, y: 355, width: 320, height: 260, annotations: { main: "Pôles complexes conjugués", poles: "-0.70+1.87i;-0.70-1.87i", zeros: "", realMin: "-4", realMax: "1", imagMin: "-3", imagMax: "3" } }),
    ],
  },
  {
    id: "pi-stability-margins",
    title: "Correction PI — marges de stabilité",
    category: "Automatique",
    description: "Boucle fermée compacte et comparaison fréquentielle avant/après correction PI, avec cassure une décade sous la coupure, pentes asymptotiques et marges de phase et de gain.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/18289/18289-sciences-industrielles-2025.pdf",
    license: "Original creation — STEM control-systems conventions",
    objects: [
      o("pi-title", { kind: "text", x: 285, y: 30, text: "Boucle fermée avec correcteur proportionnel-intégral" }),
      o("pi-input", { kind: "signal-arrow", x: 25, y: 100, x2: 100, y2: 100, annotations: { main: "E(p)" }, bindings: { endId: "pi-sum", endPort: "input-left" }, style: concours() }),
      o("pi-sum", { kind: "summing-junction", x: 100, y: 75, width: 50, height: 50, annotations: { left: "+", top: "", bottom: "−" } }),
      o("pi-error", { kind: "signal-arrow", x: 150, y: 100, x2: 220, y2: 100, annotations: { main: "ε(p)" }, bindings: { startId: "pi-sum", startPort: "output", endId: "pi-corrector", endPort: "input" }, style: concours() }),
      o("pi-corrector", { kind: "transfer-block", x: 220, y: 70, width: 110, height: 60, annotations: { main: "C_{PI}(p)" } }),
      o("pi-command", { kind: "signal-arrow", x: 330, y: 100, x2: 390, y2: 100, annotations: { main: "U(p)" }, bindings: { startId: "pi-corrector", startPort: "output", endId: "pi-process", endPort: "input" }, style: concours() }),
      o("pi-process", { kind: "transfer-block", x: 390, y: 70, width: 110, height: 60, annotations: { main: "H(p)" } }),
      o("pi-forward", { kind: "signal-arrow", x: 500, y: 100, x2: 550, y2: 100, annotations: { main: "" }, bindings: { startId: "pi-process", startPort: "output", endId: "pi-takeoff", endPort: "branch" }, style: concours() }),
      o("pi-takeoff", { kind: "takeoff-point", x: 540, y: 90, width: 20, height: 20 }),
      o("pi-output", { kind: "signal-arrow", x: 550, y: 100, x2: 675, y2: 100, annotations: { main: "S(p)" }, bindings: { startId: "pi-takeoff", startPort: "branch" }, style: concours() }),
      o("pi-return-down", { kind: "line", x: 550, y: 100, x2: 550, y2: 180, bindings: { startId: "pi-takeoff", startPort: "branch" }, style: concours() }),
      o("pi-measure-input", { kind: "signal-arrow", x: 550, y: 180, x2: 470, y2: 180, annotations: { main: "" }, bindings: { endId: "pi-measure", endPort: "input" }, style: concours() }),
      o("pi-measure", { kind: "transfer-block", x: 360, y: 150, width: 110, height: 60, annotations: { main: "H_m(p)" } }),
      o("pi-return-line", { kind: "line", x: 360, y: 180, x2: 125, y2: 180, bindings: { startId: "pi-measure", startPort: "output" }, style: concours() }),
      o("pi-return-up", { kind: "signal-arrow", x: 125, y: 180, x2: 125, y2: 125, annotations: { main: "" }, bindings: { endId: "pi-sum", endPort: "input-bottom" }, style: concours() }),

      o("pi-before-frame", { kind: "bode-diagram", x: 25, y: 230, width: 420, height: 300, annotations: { title: "Boucle ouverte — avant correction", transferFunction: "L_0(p)", omegaMin: "0.1", omegaMax: "1000", gainMin: "-60", gainMax: "40", phaseMin: "-180", phaseMax: "0", frequencyUnit: "rad/s" } }),
      o("pi-before-module-real", { kind: "bode-trace", x: 25, y: 230, width: 420, height: 300, annotations: { channel: "module", traceType: "réel", model: "deuxième ordre", gain: "1", omega0: "10", damping: "0.7", main: "L_0" }, style: concours(2.2) }),
      o("pi-before-phase-real", { kind: "bode-trace", x: 25, y: 230, width: 420, height: 300, annotations: { channel: "phase", traceType: "réel", model: "deuxième ordre", gain: "1", omega0: "10", damping: "0.7", main: "L_0" }, style: concours(2.2) }),
      o("pi-before-module-asymptote", { kind: "bode-trace", x: 25, y: 230, width: 420, height: 300, annotations: { channel: "module", traceType: "asymptotique", model: "deuxième ordre", gain: "1", omega0: "10", damping: "0.7", main: "" }, style: concours(1.2, "dashed") }),
      o("pi-before-phase-asymptote", { kind: "bode-trace", x: 25, y: 230, width: 420, height: 300, annotations: { channel: "phase", traceType: "asymptotique", model: "deuxième ordre", gain: "1", omega0: "10", damping: "0.7", main: "" }, style: concours(1.2, "dashed") }),

      o("pi-after-frame", { kind: "bode-diagram", x: 475, y: 230, width: 420, height: 300, annotations: { title: "Boucle ouverte — après correction PI", transferFunction: "L(p)=C_{PI}(p)L_0(p)", omegaMin: "0.1", omegaMax: "1000", gainMin: "-60", gainMax: "40", phaseMin: "-180", phaseMax: "0", frequencyUnit: "rad/s" } }),
      o("pi-after-module-real", { kind: "bode-trace", x: 475, y: 230, width: 420, height: 300, annotations: { channel: "module", traceType: "réel", model: "PI", gain: "1", omega0: "1", damping: "0.7", main: "L" }, style: concours(2.2) }),
      o("pi-after-phase-real", { kind: "bode-trace", x: 475, y: 230, width: 420, height: 300, annotations: { channel: "phase", traceType: "réel", model: "PI", gain: "1", omega0: "1", damping: "0.7", main: "L" }, style: concours(2.2) }),
      o("pi-after-module-asymptote", { kind: "bode-trace", x: 475, y: 230, width: 420, height: 300, annotations: { channel: "module", traceType: "asymptotique", model: "PI", gain: "1", omega0: "1", damping: "0.7", main: "" }, style: concours(1.2, "dashed") }),
      o("pi-after-phase-asymptote", { kind: "bode-trace", x: 475, y: 230, width: 420, height: 300, annotations: { channel: "phase", traceType: "asymptotique", model: "PI", gain: "1", omega0: "1", damping: "0.7", main: "" }, style: concours(1.2, "dashed") }),
      o("pi-integral-break", { kind: "bode-break", x: 620, y: 264, x2: 620, y2: 502, annotations: { main: "ω_i=ω_c/10" }, style: concours(1.2, "dashed") }),
      o("pi-low-frequency-slope", { kind: "bode-slope", x: 533, y: 286, x2: 620, y2: 330, annotations: { main: "-20 dB/décade", slope: "-20" }, style: concours(1.5) }),
      o("pi-phase-margin", { kind: "stability-margin", x: 475, y: 230, width: 420, height: 300, annotations: { marginType: "phase", omegaC: "10", marginValue: "45", main: "M_φ" }, style: concours(1.2, "dashed") }),
      o("pi-gain-margin", { kind: "stability-margin", x: 475, y: 230, width: 420, height: 300, annotations: { marginType: "gain", omegaC: "100", marginValue: "12", main: "M_G" }, style: concours(1.2, "dashed") }),
    ],
  },
  {
    id: "motorized-gate-systems",
    title: "Portail motorisé — chaîne fonctionnelle, stm et chronogramme",
    category: "Systèmes & SysML",
    description: "STEM reference sheet combining an information-and-energy chain, a SysML v1 state machine, and coherent timing diagrams for a motorized gate.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://eduscol.education.fr/sti/sites/eduscol.education.fr.sti/files/textes/cpge/cpge-technologie-et-sciences-industrielles-tsi/17201-programme-de-sii-filiere-tsi-2021.pdf",
    license: "Original creation — SysML v1 and STEM functional-chain conventions",
    objects: [
      o("gate-ibd-frame", { kind: "sysml-frame", x: 20, y: 18, width: 860, height: 147, annotations: { diagram: "ibd", name: "Portail motorisé — chaîne fonctionnelle" } }),
      o("gate-sensors", { kind: "functional-block", x: 45, y: 63, width: 125, height: 72, annotations: { function: "Acquérir", constituent: "Capteurs" } }),
      o("gate-control", { kind: "functional-block", x: 220, y: 63, width: 130, height: 72, annotations: { function: "Traiter", constituent: "Carte de commande" } }),
      o("gate-preactuator", { kind: "functional-block", x: 400, y: 63, width: 130, height: 72, annotations: { function: "Distribuer", constituent: "Préactionneur" } }),
      o("gate-motor", { kind: "functional-block", x: 580, y: 63, width: 125, height: 72, annotations: { function: "Convertir", constituent: "Moteur-réducteur" } }),
      o("gate-portal", { kind: "functional-block", x: 755, y: 63, width: 105, height: 72, annotations: { function: "Agir", constituent: "Portail" } }),
      o("gate-flow-position", { kind: "typed-flow", x: 170, y: 99, x2: 220, y2: 99, annotations: { flow: "information", main: "position" }, bindings: { startId: "gate-sensors", startPort: "output", endId: "gate-control", endPort: "input" }, style: concours() }),
      o("gate-flow-command", { kind: "typed-flow", x: 350, y: 99, x2: 400, y2: 99, annotations: { flow: "information", main: "commande" }, bindings: { startId: "gate-control", startPort: "output", endId: "gate-preactuator", endPort: "input" }, style: concours() }),
      o("gate-flow-electric", { kind: "typed-flow", x: 530, y: 99, x2: 580, y2: 99, annotations: { flow: "énergie", main: "électrique" }, bindings: { startId: "gate-preactuator", startPort: "output", endId: "gate-motor", endPort: "input" }, style: concours() }),
      o("gate-flow-mechanical", { kind: "typed-flow", x: 705, y: 99, x2: 755, y2: 99, annotations: { flow: "énergie", main: "mécanique" }, bindings: { startId: "gate-motor", startPort: "output", endId: "gate-portal", endPort: "input" }, style: concours() }),
      o("gate-stm-frame", { kind: "sysml-frame", x: 20, y: 180, width: 860, height: 205, annotations: { diagram: "stm", name: "Portail motorisé" } }),
      o("gate-initial", { kind: "state-pseudostate", x: 52, y: 251, width: 30, height: 30, annotations: { pseudostate: "initial" } }),
      o("gate-closed", { kind: "state-node", x: 105, y: 230, width: 125, height: 70, annotations: { name: "Fermé", entry: "arrêter moteur", do: "", exit: "" } }),
      o("gate-opening", { kind: "state-node", x: 300, y: 230, width: 130, height: 70, annotations: { name: "Ouverture", entry: "", do: "ouvrir", exit: "" } }),
      o("gate-open", { kind: "state-node", x: 515, y: 230, width: 125, height: 70, annotations: { name: "Ouvert", entry: "arrêter moteur", do: "", exit: "" } }),
      o("gate-closing", { kind: "state-node", x: 675, y: 310, width: 140, height: 65, annotations: { name: "Fermeture", entry: "", do: "fermer", exit: "" } }),
      o("gate-choice", { kind: "choice-junction", x: 470, y: 327, width: 38, height: 38 }),
      o("gate-init-transition", { kind: "state-transition", x: 82, y: 266, x2: 105, y2: 265, annotations: { event: "", guard: "", action: "" }, bindings: { startId: "gate-initial", startPort: "right", endId: "gate-closed", endPort: "left" }, style: concours() }),
      o("gate-start-transition", { kind: "state-transition", x: 230, y: 265, x2: 300, y2: 265, annotations: { event: "demande", guard: "sécurité", action: "" }, bindings: { startId: "gate-closed", startPort: "right", endId: "gate-opening", endPort: "left" }, style: concours() }),
      o("gate-open-transition", { kind: "state-transition", x: 430, y: 265, x2: 515, y2: 265, annotations: { event: "fin_ouverture", guard: "", action: "" }, bindings: { startId: "gate-opening", startPort: "right", endId: "gate-open", endPort: "left" }, style: concours() }),
      o("gate-delay-transition", { kind: "state-transition", x: 577.5, y: 300, x2: 745, y2: 310, annotations: { event: "temporisation", guard: "", action: "fermer" }, bindings: { startId: "gate-open", startPort: "bottom", endId: "gate-closing", endPort: "top" }, style: concours() }),
      o("gate-choice-in", { kind: "state-transition", x: 675, y: 342.5, x2: 508, y2: 346, annotations: { event: "capteur", guard: "", action: "" }, bindings: { startId: "gate-closing", startPort: "left", endId: "gate-choice", endPort: "right" }, style: concours() }),
      o("gate-obstacle-transition", { kind: "state-transition", x: 489, y: 327, x2: 365, y2: 300, annotations: { event: "", guard: "obstacle", action: "inverser" }, bindings: { startId: "gate-choice", startPort: "top", endId: "gate-opening", endPort: "bottom" }, style: concours() }),
      o("gate-close-transition", { kind: "state-transition", x: 470, y: 346, x2: 167.5, y2: 300, annotations: { event: "", guard: "fin_fermeture", action: "" }, bindings: { startId: "gate-choice", startPort: "left", endId: "gate-closed", endPort: "bottom" }, style: concours() }),
      o("gate-timing-request", { kind: "chronogram-lane", x: 40, y: 398, width: 820, height: 38, annotations: { signal: "demande", waveform: "0,1,0,0,0", chronogram: "binaire", times: "" } }),
      o("gate-timing-open", { kind: "chronogram-lane", x: 40, y: 438, width: 820, height: 38, annotations: { signal: "fin_ouverture", waveform: "0,0,1,0,0", chronogram: "binaire", times: "" } }),
      o("gate-timing-obstacle", { kind: "chronogram-lane", x: 40, y: 478, width: 820, height: 38, annotations: { signal: "obstacle", waveform: "0,0,0,1,0", chronogram: "binaire", times: "" } }),
      o("gate-timing-command", { kind: "chronogram-lane", x: 40, y: 518, width: 820, height: 38, annotations: { signal: "commande moteur", waveform: "0,1,0,-1,0", chronogram: "analogique", times: "t_0,t_1,t_2,t_3,t_4" } }),
    ],
  },
  {
    id: "sysml-requirements-architecture",
    title: "Portail motorisé — REQ, BDD et IBD SysML",
    category: "Systèmes & SysML",
    description: "STEM reference sheet linking requirements, block decomposition, and the internal architecture of a motorized gate.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/18284/18284-si-psi.pdf",
    license: "Original creation — STEM SysML v1 conventions",
    objects: [
      o("sra-req-frame", { kind: "sysml-frame", x: 15, y: 15, width: 410, height: 250, annotations: { diagram: "req", name: "Portail motorisé — exigences" } }),
      o("sra-bdd-frame", { kind: "sysml-frame", x: 440, y: 15, width: 445, height: 250, annotations: { diagram: "bdd", name: "Portail motorisé — définition" } }),
      o("sra-ibd-frame", { kind: "sysml-frame", x: 15, y: 280, width: 870, height: 265, annotations: { diagram: "ibd", name: "Portail motorisé — architecture interne" } }),

      o("sra-req-system", { kind: "sysml-requirement", x: 125, y: 48, width: 190, height: 90, annotations: { name: "Sécurité du portail", reqId: "REQ-SEC-00", statement: "Le portail doit déplacer le vantail en sécurité." } }),
      o("sra-req-speed", { kind: "sysml-requirement", x: 35, y: 155, width: 170, height: 90, annotations: { name: "Vitesse limitée", reqId: "REQ-SEC-01", statement: "La vitesse doit rester inférieure à 0,3 m/s." } }),
      o("sra-req-obstacle", { kind: "sysml-requirement", x: 235, y: 155, width: 170, height: 90, annotations: { name: "Détection obstacle", reqId: "REQ-SEC-02", statement: "Un obstacle doit provoquer l’inversion." } }),
      o("sra-req-containment", { kind: "sysml-requirement-link", x: 120, y: 155, x2: 220, y2: 138, annotations: { requirementRelation: "containment" }, bindings: { startId: "sra-req-speed", startPort: "top", endId: "sra-req-system", endPort: "bottom" }, style: concours(1.5) }),
      o("sra-req-derived", { kind: "sysml-requirement-link", x: 320, y: 155, x2: 220, y2: 138, annotations: { requirementRelation: "deriveReqt" }, bindings: { startId: "sra-req-obstacle", startPort: "top", endId: "sra-req-system", endPort: "bottom" }, style: concours(1.5) }),

      o("sra-block-system", { kind: "sysml-block", x: 575, y: 48, width: 180, height: 94, annotations: { name: "Portail motorisé", values: "", parts: "commande : Contrôleur; motorisation : Motorisation", references: "", operations: "" } }),
      o("sra-block-control", { kind: "sysml-block", x: 465, y: 170, width: 155, height: 72, annotations: { name: "Contrôleur", values: "", parts: "", references: "", operations: "élaborerConsigne()" } }),
      o("sra-block-motor", { kind: "sysml-block", x: 700, y: 170, width: 155, height: 72, annotations: { name: "Motorisation", values: "vitesse : Real", parts: "", references: "", operations: "" } }),
      o("sra-compose-control", { kind: "sysml-structural-link", x: 542.5, y: 170, x2: 665, y2: 142, annotations: { structuralRelation: "composition", symbolEnd: "fin", startRole: "commande", startMultiplicity: "1", endRole: "système", endMultiplicity: "1" }, bindings: { startId: "sra-block-control", startPort: "top", endId: "sra-block-system", endPort: "bottom" }, style: concours(1.5) }),
      o("sra-compose-motor", { kind: "sysml-structural-link", x: 777.5, y: 170, x2: 665, y2: 142, annotations: { structuralRelation: "composition", symbolEnd: "fin", startRole: "motorisation", startMultiplicity: "1", endRole: "système", endMultiplicity: "1" }, bindings: { startId: "sra-block-motor", startPort: "top", endId: "sra-block-system", endPort: "bottom" }, style: concours(1.5) }),

      o("sra-part-control", { kind: "sysml-part", x: 110, y: 350, width: 180, height: 70, annotations: { name: "ctrl", blockType: "Contrôleur" }, groupId: "sra-control-group" }),
      o("sra-part-drive", { kind: "sysml-part", x: 365, y: 350, width: 170, height: 70, annotations: { name: "variateur", blockType: "Préactionneur" }, groupId: "sra-drive-group" }),
      o("sra-part-motor", { kind: "sysml-part", x: 610, y: 350, width: 180, height: 70, annotations: { name: "motorisation", blockType: "Moteur-réducteur" }, groupId: "sra-motor-group" }),
      o("sra-input-link", { kind: "sysml-connector", x: 59, y: 385, x2: 110, y2: 385, annotations: { main: "commande utilisateur" }, bindings: { startId: "sra-port-boundary-in", startPort: "branch", endId: "sra-port-control-in", endPort: "branch" }, style: concours(1.5) }),
      o("sra-command-flow", { kind: "sysml-item-flow", x: 290, y: 385, x2: 365, y2: 385, annotations: { name: "consigne", itemType: "Information", flowDirection: "début vers fin" }, bindings: { startId: "sra-port-control-out", startPort: "branch", endId: "sra-port-drive-in", endPort: "branch" }, style: concours(1.5) }),
      o("sra-power-flow", { kind: "sysml-item-flow", x: 535, y: 385, x2: 610, y2: 385, annotations: { name: "puissance", itemType: "Énergie électrique", flowDirection: "début vers fin" }, bindings: { startId: "sra-port-drive-out", startPort: "branch", endId: "sra-port-motor-in", endPort: "branch" }, style: concours(1.5) }),
      o("sra-output-link", { kind: "sysml-connector", x: 790, y: 385, x2: 834, y2: 385, annotations: { main: "mouvement" }, bindings: { startId: "sra-port-motor-out", startPort: "branch", endId: "sra-port-boundary-out", endPort: "branch" }, style: concours(1.5) }),
      o("sra-port-boundary-in", { kind: "sysml-port", x: 50, y: 376, width: 18, height: 18, annotations: { name: "entrée", interfaceType: "IHM", portDirection: "out" } }),
      o("sra-port-control-in", { kind: "sysml-port", x: 101, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "in" }, groupId: "sra-control-group" }),
      o("sra-port-control-out", { kind: "sysml-port", x: 281, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "out" }, groupId: "sra-control-group" }),
      o("sra-port-drive-in", { kind: "sysml-port", x: 356, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "in" }, groupId: "sra-drive-group" }),
      o("sra-port-drive-out", { kind: "sysml-port", x: 526, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "out" }, groupId: "sra-drive-group" }),
      o("sra-port-motor-in", { kind: "sysml-port", x: 601, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "in" }, groupId: "sra-motor-group" }),
      o("sra-port-motor-out", { kind: "sysml-port", x: 781, y: 376, width: 18, height: 18, annotations: { name: "", interfaceType: "", portDirection: "out" }, groupId: "sra-motor-group" }),
      o("sra-port-boundary-out", { kind: "sysml-port", x: 825, y: 376, width: 18, height: 18, annotations: { name: "sortie", interfaceType: "Mouvement", portDirection: "out" } }),
      o("sra-ibd-note", { kind: "text", x: 78, y: 500, text: "Connecteurs orientés par ports - flux d’élément typés information et énergie" }),
    ],
  },
  {
    id: "young-double-slit-interference",
    title: "Interférences de Young — doubles fentes",
    category: "Ondes & interférences",
    description: "Expérience de Young avec sources cohérentes S1 et S2, différence de marche, franges et profil d’intensité.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://www.concours-commun-inp.fr/_resource/annales%20%C3%A9crits/2024/MP/2024_MP5P.pdf?download=true",
    license: "Original creation — STEM wave-optics conventions",
    objects: [
      o("young-title", { kind: "text", x: 300, y: 50, text: "Interférences de Young - doubles fentes" }),
      o("young-source", { kind: "wave-source", x: 50, y: 220, width: 70, height: 70, annotations: { name: "S", sourceType: "ponctuelle", phase: "0" } }),
      o("young-front", { kind: "wavefront", x: 150, y: 190, width: 150, height: 130, annotations: { wavefrontType: "circulaire", direction: "droite", main: "φ = constante" } }),
      o("young-aperture", { kind: "aperture-array", x: 340, y: 175, width: 70, height: 160, annotations: { apertureType: "trous d’Young", count: "2", spacing: "a", opening: "b" } }),
      o("young-screen", { kind: "fringe-screen", x: 700, y: 160, width: 150, height: 190, annotations: { screenName: "Écran", pointName: "M", fringeCount: "7", fringeSpacing: "i" } }),
      o("young-incoming", { kind: "wave-path", x: 85, y: 255, x2: 340, y2: 255, annotations: { main: "SO", medium: "n = 1", pathStyle: "réel" }, bindings: { startId: "young-source", startPort: "branch", endId: "young-aperture", endPort: "left" }, style: concours(1.5) }),
      o("young-path-1", { kind: "wave-path", x: 375, y: 215, x2: 700, y2: 255, annotations: { main: "S_1M", medium: "n = 1", pathStyle: "réel" }, bindings: { endId: "young-screen", endPort: "left" }, style: concours(1.5) }),
      o("young-path-2", { kind: "wave-path", x: 375, y: 295, x2: 700, y2: 255, annotations: { main: "S_2M", medium: "n = 1", pathStyle: "réel" }, bindings: { endId: "young-screen", endPort: "left" }, style: concours(1.5) }),
      o("young-formula", { kind: "equation", x: 75, y: 400, width: 325, height: 75, text: "\\delta(M)=S_2M-S_1M\\simeq\\frac{ax}{D},\\qquad i=\\frac{\\lambda D}{a}" }),
      o("young-profile", { kind: "intensity-profile", x: 475, y: 390, width: 300, height: 150, annotations: { profileType: "interférence", main: "I(x)", fringeCount: "7" } }),
    ],
  },
  {
    id: "fraunhofer-single-slit-diffraction",
    title: "Diffraction de Fraunhofer — fente simple",
    category: "Ondes & interférences",
    description: "Onde plane, fente de largeur a, cône de diffraction, écran éloigné et profil sinc carré.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://www.concours-commun-inp.fr/_resource/annales%20%C3%A9crits/2024/MP/2024_MP5P.pdf?download=true",
    license: "Original creation — STEM wave-optics conventions",
    objects: [
      o("fraunhofer-title", { kind: "text", x: 275, y: 50, text: "Diffraction de Fraunhofer - fente simple" }),
      o("fraunhofer-source", { kind: "wave-source", x: 40, y: 200, width: 70, height: 70, annotations: { name: "S", sourceType: "plane", phase: "0" } }),
      o("fraunhofer-front", { kind: "wavefront", x: 130, y: 170, width: 150, height: 130, annotations: { wavefrontType: "plan", direction: "droite", main: "φ = constante" } }),
      o("fraunhofer-aperture", { kind: "aperture-array", x: 300, y: 155, width: 70, height: 160, annotations: { apertureType: "fente simple", count: "1", spacing: "", opening: "a" } }),
      o("fraunhofer-cone", { kind: "diffraction-cone", x: 350, y: 160, width: 330, height: 150, annotations: { opening: "a", angle: "θ", wavelength: "λ", distance: "D" } }),
      o("fraunhofer-screen", { kind: "fringe-screen", x: 700, y: 140, width: 150, height: 190, annotations: { screenName: "Écran", pointName: "M", fringeCount: "7", fringeSpacing: "λD/a" } }),
      o("fraunhofer-incoming", { kind: "wave-path", x: 75, y: 235, x2: 300, y2: 235, annotations: { main: "onde incidente", medium: "n = 1", pathStyle: "réel" }, bindings: { startId: "fraunhofer-source", startPort: "branch", endId: "fraunhofer-aperture", endPort: "left" }, style: concours(1.5) }),
      o("fraunhofer-axis", { kind: "wave-path", x: 370, y: 235, x2: 700, y2: 235, annotations: { main: "Oz", medium: "air", pathStyle: "auxiliaire" }, bindings: { startId: "fraunhofer-aperture", startPort: "right", endId: "fraunhofer-screen", endPort: "left" }, style: concours(1.25) }),
      o("fraunhofer-formula", { kind: "equation", x: 75, y: 400, width: 350, height: 75, text: "\\theta\\simeq\\frac{\\lambda}{a},\\qquad I(x)=I_0\\,\\mathrm{sinc}^2\\!\\left(\\frac{\\pi ax}{\\lambda D}\\right)" }),
      o("fraunhofer-profile", { kind: "intensity-profile", x: 500, y: 385, width: 300, height: 150, annotations: { profileType: "diffraction", main: "I(x)", fringeCount: "7" } }),
    ],
  },
  {
    id: "progressive-standing-waves",
    title: "Onde progressive, retard et onde stationnaire",
    category: "Ondes & interférences",
    description: "Propagation sinusoïdale avec retard et déphasage, puis superposition donnant une onde stationnaire avec nœuds et ventres.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/64/8/spe779_annexe_1373648.pdf",
    license: "Original creation — STEM mechanics and diagram conventions",
    objects: [
      o("waves-title", { kind: "text", x: 250, y: 50, text: "Propagation, retard, déphasage et onde stationnaire" }),
      o("waves-source", { kind: "wave-source", x: 50, y: 115, width: 70, height: 70, annotations: { name: "S", sourceType: "ponctuelle", phase: "φ_0" } }),
      o("waves-front", { kind: "wavefront", x: 150, y: 85, width: 180, height: 130, annotations: { wavefrontType: "circulaire", direction: "droite", main: "φ = constante" } }),
      o("waves-propagation", { kind: "wave-path", x: 85, y: 150, x2: 450, y2: 150, annotations: { main: "SM = x", medium: "c", pathStyle: "réel" }, bindings: { startId: "waves-source", startPort: "branch" }, style: concours(1.5) }),
      o("waves-delay", { kind: "equation", x: 475, y: 100, width: 350, height: 100, text: "s(M,t)=s\\!\\left(S,t-\\tau\\right),\\qquad \\tau=\\frac{SM}{c},\\qquad \\Delta\\varphi=\\omega\\tau" }),
      o("waves-progressive-label", { kind: "text", x: 100, y: 275, text: "Onde progressive sinusoïdale" }),
      o("waves-progressive", { kind: "wave", x: 125, y: 325, x2: 425, y2: 325, style: concours(1.5) }),
      o("waves-standing-label", { kind: "text", x: 500, y: 275, text: "Onde stationnaire" }),
      o("waves-standing", { kind: "standing-wave", x: 475, y: 325, x2: 825, y2: 325, annotations: { main: "y(x,t)", mode: "3", showAntinodes: "oui" }, style: concours(1.5) }),
      o("waves-standing-formula", { kind: "equation", x: 225, y: 450, width: 450, height: 75, text: "y(x,t)=2A\\cos(\\omega t)\\sin(kx),\\qquad L=3\\frac{\\lambda}{2}" }),
    ],
  },
  {
    id: "lewis-vsepr-cram",
    title: "Lewis, VSEPR et représentation de Cram",
    category: "Structures moléculaires",
    description: "Atomes avec charges et doublets, géométrie VSEPR et liaisons de Cram pleine, hachurée et indéterminée.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/65/0/spe780_annexe_1373650.pdf",
    license: "Création originale — conventions IUPAC et programme officiel PCSI",
    objects: [
      o("cram-title", { kind: "text", x: 300, y: 50, text: "Lewis - VSEPR - Cram" }),
      o("cram-carbon", { kind: "chemical-atom", x: 210, y: 220, width: 70, height: 60, annotations: { element: "C", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "0" } }),
      o("cram-fluorine", { kind: "chemical-atom", x: 390, y: 220, width: 70, height: 60, annotations: { element: "F", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("cram-chlorine", { kind: "chemical-atom", x: 210, y: 90, width: 70, height: 60, annotations: { element: "Cl", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("cram-bromine", { kind: "chemical-atom", x: 80, y: 220, width: 70, height: 60, annotations: { element: "Br", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("cram-hydrogen", { kind: "chemical-atom", x: 210, y: 380, width: 70, height: 60, annotations: { element: "H", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "0" } }),
      o("cram-bond-plane", { kind: "bond-single", x: 280, y: 250, x2: 390, y2: 250, bindings: { startId: "cram-carbon", startPort: "right", endId: "cram-fluorine", endPort: "left" }, style: concours(1.7) }),
      o("cram-bond-front", { kind: "bond-wedge-solid", x: 245, y: 220, x2: 245, y2: 150, annotations: { wideEnd: "fin" }, bindings: { startId: "cram-carbon", startPort: "top", endId: "cram-chlorine", endPort: "bottom" }, style: concours(1.7) }),
      o("cram-bond-back", { kind: "bond-wedge-hashed", x: 210, y: 250, x2: 150, y2: 250, annotations: { wideEnd: "fin" }, bindings: { startId: "cram-carbon", startPort: "left", endId: "cram-bromine", endPort: "right" }, style: concours(1.7) }),
      o("cram-bond-unspecified", { kind: "bond-wavy", x: 245, y: 280, x2: 245, y2: 380, annotations: { main: "" }, bindings: { startId: "cram-carbon", startPort: "bottom", endId: "cram-hydrogen", endPort: "top" }, style: concours(1.7) }),
      o("cram-vsepr-label", { kind: "text", x: 150, y: 500, text: "AX4 : géométrie tétraédrique" }),
      o("lewis-oxygen", { kind: "chemical-atom", x: 650, y: 165, width: 70, height: 60, annotations: { element: "O", hydrogens: "2", charge: "", isotope: "18", radical: "non", electronVacancy: "non", lonePairs: "2" } }),
      o("lewis-ammonium", { kind: "chemical-atom", x: 650, y: 325, width: 70, height: 60, annotations: { element: "N", hydrogens: "4", charge: "+", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "0" } }),
      o("lewis-label", { kind: "text", x: 625, y: 500, text: "Lewis : isotopes, charges et doublets explicites" }),
    ],
  },
  {
    id: "newman-conformations",
    title: "Conformations de Newman — décalée et éclipsée",
    category: "Structures moléculaires",
    description: "Deux projections de Newman comparant les conformations décalée et éclipsée autour d’une liaison carbone-carbone.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/65/0/spe780_annexe_1373650.pdf",
    license: "Création originale — conventions IUPAC et programme officiel PCSI",
    objects: [
      o("newman-title", { kind: "text", x: 250, y: 50, text: "Projection de Newman" }),
      o("newman-staggered", { kind: "newman-projection", x: 100, y: 140, width: 240, height: 240, annotations: { conformation: "décalée", front1: "H", front2: "H", front3: "CH_3", rear1: "H", rear2: "H", rear3: "CH_3", rotation: "0" } }),
      o("newman-equivalence", { kind: "double-arrow", x: 375, y: 260, x2: 525, y2: 260, style: concours(1.7) }),
      o("newman-eclipsed", { kind: "newman-projection", x: 560, y: 140, width: 240, height: 240, annotations: { conformation: "éclipsée", front1: "H", front2: "H", front3: "CH_3", rear1: "H", rear2: "H", rear3: "CH_3", rotation: "60" } }),
      o("newman-staggered-label", { kind: "text", x: 125, y: 450, text: "Décalée : énergie minimale" }),
      o("newman-eclipsed-label", { kind: "text", x: 575, y: 450, text: "Éclipsée : répulsions maximales" }),
    ],
  },
  {
    id: "mesomerism-sn2-mechanism",
    title: "Mésomérie et mécanisme SN2",
    category: "Structures moléculaires",
    description: "Formes mésomères, flèches de déplacement d’un doublet, flèche monoélectronique et étape SN2 annotée.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://www.concours-centrale-supelec.fr/sites/default/files/documents/X010.pdf",
    license: "Original creation — IUPAC and STEM chemistry conventions",
    objects: [
      o("mechanism-title", { kind: "text", x: 300, y: 40, text: "Mésomérie - transferts électroniques - SN2" }),
      o("mesomeric-ring-1", { kind: "skeletal-ring", x: 40, y: 60, width: 150, height: 140, annotations: { ringSize: "6", ringType: "alterné", substituent1: "O^-", substituent2: "" } }),
      o("mesomeric-arrow", { kind: "mesomeric-arrow", x: 255, y: 130, x2: 440, y2: 130, annotations: { main: "" }, style: concours(1.7) }),
      o("mesomeric-ring-2", { kind: "skeletal-ring", x: 510, y: 60, width: 150, height: 140, annotations: { ringSize: "6", ringType: "alterné", substituent1: "O", substituent2: "^-" } }),
      o("mesomeric-oxygen", { kind: "chemical-atom", x: 710, y: 100, width: 70, height: 60, annotations: { element: "O", hydrogens: "0", charge: "-", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("radical-left", { kind: "chemical-atom", x: 300, y: 230, width: 70, height: 60, annotations: { element: "Cl", hydrogens: "0", charge: "", isotope: "", radical: "oui", electronVacancy: "non", lonePairs: "3" } }),
      o("radical-right", { kind: "chemical-atom", x: 500, y: 230, width: 70, height: 60, annotations: { element: "Cl", hydrogens: "0", charge: "", isotope: "", radical: "oui", electronVacancy: "non", lonePairs: "3" } }),
      o("fishhook-transfer", { kind: "single-electron-arrow", x: 370, y: 260, x2: 500, y2: 260, annotations: { main: "1 e^-", curvature: "gauche" }, bindings: { startId: "radical-left", startPort: "right", endId: "radical-right", endPort: "left" }, style: concours(1.5) }),
      o("sn2-nucleophile", { kind: "chemical-atom", x: 40, y: 390, width: 70, height: 60, annotations: { element: "O", hydrogens: "1", charge: "-", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("sn2-carbon", { kind: "chemical-atom", x: 300, y: 390, width: 70, height: 60, annotations: { element: "C", hydrogens: "3", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "0" } }),
      o("sn2-bromine", { kind: "chemical-atom", x: 470, y: 390, width: 70, height: 60, annotations: { element: "Br", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "3" } }),
      o("sn2-attack", { kind: "electron-pair-arrow", x: 110, y: 420, x2: 300, y2: 420, annotations: { main: "2 e^-", curvature: "gauche" }, bindings: { startId: "sn2-nucleophile", startPort: "right", endId: "sn2-carbon", endPort: "left" }, style: concours(1.5) }),
      o("sn2-leaving-bond", { kind: "bond-single", x: 370, y: 420, x2: 470, y2: 420, bindings: { startId: "sn2-carbon", startPort: "right", endId: "sn2-bromine", endPort: "left" }, style: concours(1.7) }),
      o("sn2-reaction", { kind: "reaction-arrow", x: 575, y: 420, x2: 800, y2: 420, annotations: { above: "", below: "", reagent: "SN2", solvent: "acétone", temperature: "20 °C", duration: "rapide" }, style: concours(1.7) }),
      o("sn2-product", { kind: "chemical-atom", x: 810, y: 390, width: 70, height: 60, annotations: { element: "R", hydrogens: "0", charge: "", isotope: "", radical: "non", electronVacancy: "non", lonePairs: "0" } }),
      o("mechanism-note", { kind: "text", x: 250, y: 525, text: "La queue de flèche part toujours de la source d’électrons" }),
    ],
  },
  {
    id: "mechanical-transmissions",
    title: "Transmissions mécaniques usuelles",
    category: "Mécanique",
    description: "STEM reference sheet for gear, rack-and-pinion, belt-and-pulley, and screw-and-nut transmissions.",
    sourceName: "STEM mechanical power-transmission reference",
    sourceUrl: "https://sti.eduscol.education.fr/referentiels-par-savoirs-cpge-cpge-physique-technologie-ptsi-ptpt-cycle-complet-2021-s3-resoudre-26",
    license: "Création originale – conventions des schémas cinématiques français",
    objects: [
      o("mt-title", { kind: "text", x: 300, y: 75, text: "Transmissions mécaniques usuelles" }),
      o("mt-gears", { kind: "gear-pair", x: 100, y: 125, width: 170, height: 110, annotations: { driver: "Z_1", driven: "Z_2" } }),
      o("mt-rack", { kind: "rack-pinion", x: 550, y: 125, width: 180, height: 120, annotations: { pinion: "Z", rack: "x" } }),
      o("mt-gears-label", { kind: "text", x: 100, y: 275, text: "Engrenage extérieur" }),
      o("mt-rack-label", { kind: "text", x: 525, y: 275, text: "Pignon-crémaillère" }),
      o("mt-belt", { kind: "belt-drive", x: 90, y: 350, width: 190, height: 120, annotations: { driver: "D_1", driven: "D_2" } }),
      o("mt-screw", { kind: "screw-nut", x: 550, y: 350, width: 180, height: 105, annotations: { pitch: "p" } }),
      o("mt-belt-label", { kind: "text", x: 100, y: 500, text: "Poulies-courroie" }),
      o("mt-screw-label", { kind: "text", x: 550, y: 500, text: "Vis-écrou" }),
      o("mt-law-gears", { kind: "text", x: 300, y: 200, text: "ω₂/ω₁ = −Z₁/Z₂" }),
      o("mt-law-rack", { kind: "text", x: 750, y: 200, text: "v = Rω" }),
    ],
  },
  {
    id: "advanced-mechanical-transmissions",
    title: "Transmissions mécaniques avancées",
    category: "Mécanique",
    description: "STEM reference sheet for worm gear, planetary gear train, and cam-follower mechanisms with functional reference points.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/15776/15776-caplp-ext-2023-gm-opt-prod-epreuve-1.pdf",
    license: "Création originale d’après des sujets officiels Éduscol et les conventions des schémas cinématiques français",
    objects: [
      o("amt-title", { kind: "text", x: 275, y: 65, text: "Transmissions mécaniques avancées" }),
      o("amt-worm", { kind: "worm-gear", x: 75, y: 140, width: 180, height: 125, annotations: { worm: "Z_v", wheel: "Z_r" } }),
      o("amt-planetary", { kind: "planetary-gear", x: 350, y: 110, width: 180, height: 180, annotations: { sun: "Z_s", ring: "Z_c", carrier: "PS" } }),
      o("amt-cam", { kind: "cam-follower", x: 675, y: 125, width: 150, height: 160, annotations: { cam: "C", follower: "S" } }),
      o("amt-worm-label", { kind: "text", x: 75, y: 325, text: "Roue et vis sans fin" }),
      o("amt-planetary-label", { kind: "text", x: 350, y: 325, text: "Train épicycloïdal" }),
      o("amt-cam-label", { kind: "text", x: 675, y: 325, text: "Came et poussoir" }),
      o("amt-worm-note", { kind: "text", x: 75, y: 390, text: "entrée : vis · sortie : roue" }),
      o("amt-planetary-note", { kind: "text", x: 350, y: 390, text: "soleil · couronne · porte-satellites" }),
      o("amt-cam-note", { kind: "text", x: 675, y: 390, text: "rotation → translation" }),
    ],
  },
  {
    id: "electromechanical-power-chain",
    title: "Chaîne d’énergie électromécanique",
    category: "Mécanique",
    description: "Chaîne de puissance de concours avec moteur, réducteur, embrayage, frein de sécurité et organe entraîné.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/10231/10231-sujet-mc-ta-session-2018-dossier-technique-complet-copie.pdf",
    license: "Création originale d’après une chaîne cinématique officielle Éduscol",
    objects: [
      o("pc-title", { kind: "text", x: 270, y: 65, text: "Chaîne d’énergie électromécanique" }),
      o("pc-electric-input", { kind: "signal-arrow", x: 20, y: 235, x2: 75, y2: 235, annotations: { main: "u_m, i_m" }, bindings: { endId: "pc-motor", endPort: "electrical" }, style: concours() }),
      o("pc-motor", { kind: "electric-motor", x: 75, y: 190, width: 130, height: 90, annotations: { main: "M" } }),
      o("pc-motor-shaft", { kind: "line", x: 205, y: 235, x2: 275, y2: 235, bindings: { startId: "pc-motor", startPort: "shaft", endId: "pc-reducer", endPort: "input" }, style: concours(2.4) }),
      o("pc-reducer", { kind: "gear-reducer", x: 275, y: 190, width: 140, height: 90, annotations: { main: "r" } }),
      o("pc-reduced-shaft", { kind: "line", x: 415, y: 235, x2: 485, y2: 235, bindings: { startId: "pc-reducer", startPort: "output", endId: "pc-clutch", endPort: "input" }, style: concours(2.4) }),
      o("pc-clutch", { kind: "clutch", x: 485, y: 190, width: 130, height: 90, annotations: { main: "E" } }),
      o("pc-output-shaft", { kind: "line", x: 615, y: 235, x2: 720, y2: 235, bindings: { startId: "pc-clutch", startPort: "output" }, style: concours(2.4) }),
      o("pc-pulley", { kind: "pulley", x: 700, y: 192, width: 85, height: 85 }),
      o("pc-brake-branch", { kind: "line", x: 655, y: 235, x2: 655, y2: 285, bindings: { endId: "pc-brake", endPort: "shaft" }, style: concours(2.4) }),
      o("pc-brake", { kind: "brake", x: 585, y: 295, width: 130, height: 110, rotation: 90, annotations: { main: "F" } }),
      o("pc-motor-label", { kind: "text", x: 80, y: 325, text: "Convertir" }),
      o("pc-reducer-label", { kind: "text", x: 280, y: 325, text: "Adapter" }),
      o("pc-clutch-label", { kind: "text", x: 500, y: 325, text: "Distribuer / accoupler" }),
      o("pc-load-label", { kind: "text", x: 715, y: 325, text: "Agir" }),
      o("pc-motor-quantities", { kind: "text", x: 200, y: 175, text: "C_m, ω_m" }),
      o("pc-output-quantities", { kind: "text", x: 615, y: 175, text: "C_s, ω_s" }),
      o("pc-note", { kind: "text", x: 200, y: 450, text: "Le frein est lié au bâti et agit sur l’arbre de sortie." }),
    ],
  },
  {
    id: "hydraulic-double-acting-cylinder",
    title: "Circuit hydraulique – vérin double effet",
    category: "Mécanique",
    description: "Groupe hydraulique ISO 1219 avec pompe motorisée, limiteur de pression, distributeur 4/3 à centre fermé et vérin double effet.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/17270/17270-cgm-mm-2024-dc-mmcm-partie-copie.pdf",
    license: "Création originale d’après les symboles hydrauliques utilisés au Concours général des métiers",
    objects: [
      o("hc-title", { kind: "text", x: 250, y: 50, text: "Circuit hydraulique – vérin double effet" }),
      o("hc-cylinder", { kind: "hydraulic-cylinder", x: 560, y: 80, width: 180, height: 100, annotations: { main: "1A" } }),
      o("hc-valve", { kind: "hydraulic-valve-4-3", x: 205, y: 190, width: 200, height: 130, annotations: { main: "1V" } }),
      o("hc-a-up", { kind: "line", x: 290, y: 190, x2: 290, y2: 150, bindings: { startId: "hc-valve", startPort: "A" }, style: concours(2.4) }),
      o("hc-a-across", { kind: "line", x: 290, y: 150, x2: 614, y2: 150, style: concours(2.4) }),
      o("hc-a-cylinder", { kind: "line", x: 614, y: 150, x2: 614, y2: 180, bindings: { endId: "hc-cylinder", endPort: "A" }, style: concours(2.4) }),
      o("hc-b-up", { kind: "line", x: 320, y: 190, x2: 320, y2: 120, bindings: { startId: "hc-valve", startPort: "B" }, style: concours(2.4) }),
      o("hc-b-across", { kind: "line", x: 320, y: 120, x2: 686, y2: 120, style: concours(2.4) }),
      o("hc-b-cylinder", { kind: "line", x: 686, y: 120, x2: 686, y2: 180, bindings: { endId: "hc-cylinder", endPort: "B" }, style: concours(2.4) }),
      o("hc-pump", { kind: "hydraulic-pump", x: 245, y: 340, width: 90, height: 110, annotations: { main: "0P" } }),
      o("hc-pressure", { kind: "line", x: 290, y: 320, x2: 290, y2: 340, bindings: { startId: "hc-valve", startPort: "P", endId: "hc-pump", endPort: "P" }, style: concours(2.4) }),
      o("hc-motor", { kind: "electric-motor", x: 70, y: 350, width: 130, height: 90, annotations: { main: "M" } }),
      o("hc-motor-pump", { kind: "line", x: 200, y: 395, x2: 245, y2: 395, bindings: { startId: "hc-motor", startPort: "shaft", endId: "hc-pump", endPort: "shaft" }, style: concours(2.4) }),
      o("hc-electric-input", { kind: "signal-arrow", x: 20, y: 395, x2: 70, y2: 395, annotations: { main: "u, i" }, bindings: { endId: "hc-motor", endPort: "electrical" }, style: concours() }),
      o("hc-reservoir", { kind: "hydraulic-reservoir", x: 240, y: 475, width: 100, height: 70, annotations: { main: "0T" } }),
      o("hc-suction", { kind: "line", x: 290, y: 450, x2: 290, y2: 475, bindings: { startId: "hc-pump", startPort: "T", endId: "hc-reservoir", endPort: "T" }, style: concours(2.4) }),
      o("hc-relief", { kind: "pressure-relief-valve", x: 380, y: 289, width: 140, height: 110, rotation: 90, annotations: { main: "p_0" } }),
      o("hc-relief-pressure", { kind: "line", x: 290, y: 330, x2: 395, y2: 330, bindings: { endId: "hc-relief", endPort: "P" }, style: concours(2.4) }),
      o("hc-relief-return", { kind: "line", x: 505, y: 330, x2: 520, y2: 330, bindings: { startId: "hc-relief", startPort: "T" }, style: concours(2.4) }),
      o("hc-valve-return", { kind: "line", x: 320, y: 320, x2: 520, y2: 320, bindings: { startId: "hc-valve", startPort: "T" }, style: concours(2.4) }),
      o("hc-return-down", { kind: "line", x: 520, y: 320, x2: 520, y2: 475, style: concours(2.4) }),
      o("hc-return-tank", { kind: "line", x: 520, y: 475, x2: 290, y2: 475, bindings: { endId: "hc-reservoir", endPort: "T" }, style: concours(2.4) }),
      o("hc-pressure-label", { kind: "text", x: 300, y: 350, text: "P" }),
      o("hc-return-label", { kind: "text", x: 525, y: 350, text: "T" }),
      o("hc-note", { kind: "text", x: 575, y: 225, text: "A/B : conduites de travail" }),
    ],
  },
  {
    id: "electropneumatic-double-acting-cylinder",
    title: "Circuit électropneumatique – vérin double effet",
    category: "Mécanique",
    description: "Circuit ISO 1219 avec source d’air, conditionnement, distributeur 5/2 monostable, réglages de vitesse à l’échappement et vérin double effet.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/6319/6319-e2-cor-m-2015.pdf",
    license: "Création originale d’après un schéma pneumatique officiel Éduscol",
    objects: [
      o("pn-title", { kind: "text", x: 250, y: 45, text: "Circuit électropneumatique – vérin double effet" }),
      o("pn-cylinder", { kind: "pneumatic-cylinder", x: 600, y: 60, width: 180, height: 100, annotations: { main: "1A1" } }),
      o("pn-cap-control", { kind: "one-way-flow-control", x: 584, y: 180, width: 140, height: 90, rotation: 90, annotations: { main: "1V2" } }),
      o("pn-rod-control", { kind: "one-way-flow-control", x: 656, y: 180, width: 140, height: 90, rotation: 90, scaleX: -1, annotations: { main: "1V3" } }),
      o("pn-cap-cylinder", { kind: "line", x: 654, y: 155, x2: 654, y2: 160, bindings: { startId: "pn-cap-control", startPort: "1", endId: "pn-cylinder", endPort: "cap" }, style: concours(2.4) }),
      o("pn-rod-cylinder", { kind: "line", x: 726, y: 155, x2: 726, y2: 160, bindings: { startId: "pn-rod-control", startPort: "2", endId: "pn-cylinder", endPort: "rod-side" }, style: concours(2.4) }),
      o("pn-valve", { kind: "pneumatic-valve-5-2", x: 270, y: 320, width: 180, height: 125, annotations: { main: "1V1", actuator: "1M1" } }),
      o("pn-a-up", { kind: "line", x: 400.5, y: 320, x2: 400.5, y2: 300, bindings: { startId: "pn-valve", startPort: "2" }, style: concours(2.4) }),
      o("pn-a-across", { kind: "line", x: 400.5, y: 300, x2: 654, y2: 300, style: concours(2.4) }),
      o("pn-a-control", { kind: "line", x: 654, y: 300, x2: 654, y2: 295, bindings: { endId: "pn-cap-control", endPort: "2" }, style: concours(2.4) }),
      o("pn-b-up", { kind: "line", x: 373.5, y: 320, x2: 373.5, y2: 275, bindings: { startId: "pn-valve", startPort: "4" }, style: concours(2.4) }),
      o("pn-b-across", { kind: "line", x: 373.5, y: 275, x2: 726, y2: 275, style: concours(2.4) }),
      o("pn-b-control", { kind: "line", x: 726, y: 275, x2: 726, y2: 295, bindings: { endId: "pn-rod-control", endPort: "1" }, style: concours(2.4) }),
      o("pn-control-signal", { kind: "signal-arrow", x: 185, y: 382.5, x2: 270, y2: 382.5, annotations: { main: "14 / 1M1" }, bindings: { endId: "pn-valve", endPort: "14" }, style: concours() }),
      o("pn-source", { kind: "pneumatic-source", x: 40, y: 440, width: 90, height: 100, rotation: 90, annotations: { main: "0P1" } }),
      o("pn-conditioning", { kind: "pneumatic-service-unit", x: 165, y: 445, width: 170, height: 90, annotations: { main: "0Z1" } }),
      o("pn-source-conditioning", { kind: "line", x: 135, y: 490, x2: 165, y2: 490, bindings: { startId: "pn-source", startPort: "P", endId: "pn-conditioning", endPort: "input" }, style: concours(2.4) }),
      o("pn-supply-across", { kind: "line", x: 335, y: 490, x2: 387, y2: 490, bindings: { startId: "pn-conditioning", startPort: "output" }, style: concours(2.4) }),
      o("pn-supply-up", { kind: "line", x: 387, y: 490, x2: 387, y2: 445, bindings: { endId: "pn-valve", endPort: "1" }, style: concours(2.4) }),
      o("pn-s-down", { kind: "line", x: 369, y: 445, x2: 369, y2: 470, bindings: { startId: "pn-valve", startPort: "5" }, style: concours(2.4) }),
      o("pn-s-across", { kind: "line", x: 369, y: 470, x2: 500, y2: 470, style: concours(2.4) }),
      o("pn-s-exhaust-line", { kind: "line", x: 500, y: 470, x2: 500, y2: 500, bindings: { endId: "pn-s-exhaust", endPort: "input" }, style: concours(2.4) }),
      o("pn-s-exhaust", { kind: "pneumatic-exhaust", x: 470, y: 500, width: 60, height: 60 }),
      o("pn-r-down", { kind: "line", x: 405, y: 445, x2: 405, y2: 460, bindings: { startId: "pn-valve", startPort: "3" }, style: concours(2.4) }),
      o("pn-r-across", { kind: "line", x: 405, y: 460, x2: 570, y2: 460, style: concours(2.4) }),
      o("pn-r-exhaust-line", { kind: "line", x: 570, y: 460, x2: 570, y2: 500, bindings: { endId: "pn-r-exhaust", endPort: "input" }, style: concours(2.4) }),
      o("pn-r-exhaust", { kind: "pneumatic-exhaust", x: 540, y: 500, width: 60, height: 60 }),
      o("pn-meter-out-note", { kind: "text", x: 475, y: 210, text: "Réglage à l’échappement" }),
      o("pn-control-note", { kind: "text", x: 50, y: 375, text: "Commande électrique" }),
    ],
  },
  {
    id: "gps-technical-drawing-reference",
    title: "Planche de référence — dessin technique et GPS",
    category: "Dessin technique",
    description: "Exemple français avec arêtes cachées, axe, plan de coupe A–A, hachures, référence, tolérances géométriques et état de surface ISO 21920.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://sti.eduscol.education.fr/sites/eduscol.education.fr.sti/files/concours-examens/10546/10546-concours-general-des-metiers-tu-2016-pratique-dossier-candidat.pdf",
    license: "Création originale d’après les conventions ISO 128, ISO 1101, ISO 5459 et ISO 21920 utilisées dans un plan de concours Éduscol",
    objects: [
      o("gps-title", { kind: "text", x: 225, y: 42, text: "Dessin technique — coupe et spécifications GPS" }),
      o("gps-cutting-plane", { kind: "cutting-plane", x: 95, y: 70, x2: 365, y2: 70, annotations: { main: "A" }, style: concours(2.5) }),
      o("gps-part-top", { kind: "line", x: 80, y: 125, x2: 380, y2: 125, style: concours(2.5) }),
      o("gps-part-right", { kind: "line", x: 380, y: 125, x2: 380, y2: 305, style: concours(2.5) }),
      o("gps-part-bottom", { kind: "line", x: 380, y: 305, x2: 80, y2: 305, style: concours(2.5) }),
      o("gps-part-left", { kind: "line", x: 80, y: 305, x2: 80, y2: 125, style: concours(2.5) }),
      o("gps-hidden-left", { kind: "hidden-edge", x: 205, y: 125, x2: 205, y2: 305, style: concours(1.25) }),
      o("gps-hidden-right", { kind: "hidden-edge", x: 255, y: 125, x2: 255, y2: 305, style: concours(1.25) }),
      o("gps-centre", { kind: "centre-line", x: 45, y: 215, x2: 415, y2: 215, style: concours(1.25) }),
      o("gps-section-outline", { kind: "rect", x: 650, y: 125, width: 160, height: 180, style: concours(2.5) }),
      o("gps-section-hatch", { kind: "section-hatch", x: 650, y: 125, width: 160, height: 180, style: concours(1.25) }),
      o("gps-section-centre", { kind: "centre-line", x: 620, y: 215, x2: 840, y2: 215, style: concours(1.25) }),
      o("gps-section-title", { kind: "text", x: 690, y: 330, text: "COUPE A–A" }),
      o("gps-datum-a", { kind: "datum-feature", x: 120, y: 305, x2: 120, y2: 365, annotations: { datum: "A" }, bindings: { startId: "gps-part-bottom", startPort: "segment", startRatio: .867 }, style: concours(1.25) }),
      o("gps-flatness", { kind: "feature-control-frame", x: 180, y: 125, x2: 430, y2: 345, annotations: { characteristic: "planéité", tolerance: "0,05", diameter: "non", modifier: "", datum1: "", datum2: "", datum3: "" }, bindings: { startId: "gps-part-top", startPort: "segment", startRatio: .333 }, style: concours(1.25) }),
      o("gps-perpendicularity", { kind: "feature-control-frame", x: 380, y: 250, x2: 430, y2: 395, annotations: { characteristic: "perpendicularité", tolerance: "0,02", diameter: "non", modifier: "", datum1: "A", datum2: "", datum3: "" }, bindings: { startId: "gps-part-right", startPort: "segment", startRatio: .694 }, style: concours(1.25) }),
      o("gps-position", { kind: "feature-control-frame", x: 230, y: 125, x2: 430, y2: 450, annotations: { characteristic: "position", tolerance: "0,10", diameter: "oui", modifier: "", datum1: "A", datum2: "B", datum3: "C" }, bindings: { startId: "gps-part-top", startPort: "segment", startRatio: .5 }, style: concours(1.25) }),
      o("gps-surface", { kind: "surface-texture", x: 300, y: 125, x2: 520, y2: 105, annotations: { requirement: "enlèvement", parameter: "Ra", value: "3,2", process: "", lay: "", allAround: "non" }, bindings: { startId: "gps-part-top", startPort: "segment", startRatio: .733 }, style: concours(1.25) }),
      o("gps-note", { kind: "text", x: 75, y: 525, text: "Extension dessin de définition : ISO 128 · ISO 1101 · ISO 5459 · ISO 21920" }),
    ],
  },
  {
    id: "normalized-kinematic-joints",
    title: "Liaisons mécaniques normalisées",
    category: "Mécanique",
    description: "Planche de référence des neuf liaisons usuelles en représentation plane française.",
    sourceName: "Éduscol STI – extension Liaisons cinématiques",
    sourceUrl: "https://sti.eduscol.education.fr/ressources_pedagogiques/inkscape-extension-pour-le-dessin-2d-ou-3d-de-liaisons-cinematiques",
    license: "Adaptation monochrome des représentations NF EN ISO 3952-1",
    objects: [
      o("kj-title", { kind: "text", x: 280, y: 75, text: "Liaisons mécaniques normalisées – vues planes" }),
      o("kj-pivot", { kind: "joint-pivot", x: 100, y: 125, width: 90, height: 50 }),
      o("kj-slider", { kind: "joint-slider", x: 395, y: 115, width: 110, height: 70 }),
      o("kj-cylindrical", { kind: "joint-cylindrical", x: 680, y: 115, width: 110, height: 70 }),
      o("kj-label-pivot", { kind: "text", x: 100, y: 225, text: "Pivot" }),
      o("kj-label-slider", { kind: "text", x: 385, y: 225, text: "Glissière" }),
      o("kj-label-cylindrical", { kind: "text", x: 650, y: 225, text: "Pivot glissant" }),
      o("kj-helical", { kind: "joint-helical", x: 90, y: 265, width: 110, height: 70 }),
      o("kj-ball", { kind: "joint-ball", x: 400, y: 265, width: 100, height: 70 }),
      o("kj-planar", { kind: "joint-planar", x: 690, y: 260, width: 90, height: 80 }),
      o("kj-label-helical", { kind: "text", x: 80, y: 365, text: "Hélicoïdale" }),
      o("kj-label-ball", { kind: "text", x: 400, y: 365, text: "Sphérique" }),
      o("kj-label-planar", { kind: "text", x: 670, y: 365, text: "Appui plan" }),
      o("kj-line-contact", { kind: "joint-line-contact", x: 100, y: 405, width: 90, height: 90 }),
      o("kj-annular", { kind: "joint-annular", x: 405, y: 405, width: 90, height: 90 }),
      o("kj-point-contact", { kind: "joint-point-contact", x: 690, y: 405, width: 90, height: 90 }),
      o("kj-label-line", { kind: "text", x: 50, y: 525, text: "Linéaire rectiligne" }),
      o("kj-label-annular", { kind: "text", x: 360, y: 525, text: "Linéaire annulaire" }),
      o("kj-label-point", { kind: "text", x: 650, y: 525, text: "Sphère-plan" }),
      o("kj-fixed-note", { kind: "text", x: 280, y: 550, text: "Encastrement : raccord direct entre les traits des deux solides" }),
    ],
  },
  {
    id: "slider-crank-kinematic",
    title: "Schéma cinématique bielle-manivelle",
    category: "Mécanique",
    description: "Schéma plan avec pivots A et B, glissière, bâti 0 et solides numérotés selon les conventions françaises.",
    sourceName: "Éduscol STI – extension Liaisons cinématiques",
    sourceUrl: "https://sti.eduscol.education.fr/ressources_pedagogiques/inkscape-extension-pour-le-dessin-2d-ou-3d-de-liaisons-cinematiques",
    license: "Création originale – représentations normalisées NF EN ISO 3952-1",
    objects: [
      o("sc-pivot-a", { kind: "joint-pivot", x: 120, y: 190, width: 90, height: 50 }),
      o("sc-crank", { kind: "line", x: 210, y: 215, x2: 360, y2: 285, bindings: { startId: "sc-pivot-a", startPort: "solid-1", endId: "sc-pivot-b", endPort: "solid-2" }, style: concours(3) }),
      o("sc-pivot-b", { kind: "joint-pivot", x: 360, y: 260, width: 90, height: 50 }),
      o("sc-rod", { kind: "line", x: 450, y: 285, x2: 650, y2: 278, bindings: { startId: "sc-pivot-b", startPort: "solid-1", endId: "sc-slider", endPort: "solid-1" }, style: concours(3) }),
      o("sc-slider", { kind: "joint-slider", x: 650, y: 250, width: 110, height: 70 }),
      o("sc-ground-a", { kind: "line", x: 120, y: 215, x2: 80, y2: 215, bindings: { startId: "sc-pivot-a", startPort: "solid-2" }, style: concours(3) }),
      o("sc-ground-a-down", { kind: "line", x: 80, y: 215, x2: 80, y2: 380, style: concours(3) }),
      o("sc-ground-slider", { kind: "line", x: 705, y: 320, x2: 705, y2: 380, bindings: { startId: "sc-slider", startPort: "solid-2" }, style: concours(3) }),
      o("sc-ground", { kind: "line", x: 80, y: 380, x2: 780, y2: 380, style: concours(3) }),
      o("sc-hatch-1", { kind: "line", x: 120, y: 380, x2: 100, y2: 400, style: concours() }),
      o("sc-hatch-2", { kind: "line", x: 200, y: 380, x2: 180, y2: 400, style: concours() }),
      o("sc-hatch-3", { kind: "line", x: 280, y: 380, x2: 260, y2: 400, style: concours() }),
      o("sc-hatch-4", { kind: "line", x: 720, y: 380, x2: 700, y2: 400, style: concours() }),
      o("sc-motion", { kind: "double-arrow", x: 650, y: 205, x2: 760, y2: 205, style: concours() }),
      o("sc-label-a", { kind: "text", x: 157, y: 180, text: "A" }),
      o("sc-label-b", { kind: "text", x: 397, y: 250, text: "B" }),
      o("sc-label-0", { kind: "text", x: 90, y: 425, text: "0 : bâti" }),
      o("sc-label-1", { kind: "text", x: 265, y: 225, text: "1 : manivelle" }),
      o("sc-label-2", { kind: "text", x: 515, y: 260, text: "2 : bielle" }),
      o("sc-label-3", { kind: "text", x: 675, y: 340, text: "3 : coulisseau" }),
      o("sc-title", { kind: "text", x: 310, y: 105, text: "Schéma cinématique plan – bielle-manivelle" }),
    ],
  },
  {
    id: "pendulum-forces",
    title: "Pendule et forces",
    category: "Mécanique",
    description: "Pendule dévié, poids, tension, angle et repère.",
    sourceName: "TikZ.net",
    sourceUrl: "https://tikz.net/dynamics_pendulum/",
    license: "Adapté sous CC BY-SA 4.0",
    objects: [
      o("pen-support", { kind: "line", x: 250, y: 95, x2: 470, y2: 95 }),
      o("pen-rope", { kind: "line", x: 360, y: 95, x2: 485, y2: 330 }),
      o("pen-mass", { kind: "mass", x: 445, y: 315, width: 80, height: 60, annotations: { main: "m" } }),
      o("pen-weight", { kind: "force", x: 485, y: 345, x2: 485, y2: 475, annotations: { main: "P" }, style: concours(3) }),
      o("pen-tension", { kind: "force", x: 480, y: 330, x2: 405, y2: 190, annotations: { main: "T" }, style: concours(3) }),
      o("pen-vertical", { kind: "dashed-line", x: 360, y: 95, x2: 360, y2: 390 }),
      o("pen-angle", { kind: "curve", x: 360, y: 175, x2: 398, y2: 166, control: { x: 377, y: 165 }, annotations: { main: "θ" } }),
      o("pen-label", { kind: "text", x: 395, y: 195, text: "θ" }),
    ],
  },
  {
    id: "prism-dispersion",
    title: "Dispersion par un prisme",
    category: "Optique",
    description: "Rayon incident et faisceau dispersé à travers un prisme.",
    sourceName: "TikZ.net",
    sourceUrl: "https://tikz.net/optics_prism/",
    license: "Adapté sous CC BY-SA 4.0",
    objects: [
      o("prism", { kind: "prism", x: 370, y: 190, width: 150, height: 140 }),
      o("incident", { kind: "light-ray", x: 100, y: 260, x2: 415, y2: 260, style: concours(3) }),
      o("red", { kind: "light-ray", x: 470, y: 260, x2: 760, y2: 205, style: concours(3) }),
      o("orange", { kind: "light-ray", x: 470, y: 260, x2: 760, y2: 240, style: concours(3, "dashed") }),
      o("blue", { kind: "light-ray", x: 470, y: 260, x2: 760, y2: 300, style: concours(3, "dotted") }),
      o("violet", { kind: "light-ray", x: 470, y: 260, x2: 760, y2: 335, style: concours(3, "dash-dot") }),
      o("white-light", { kind: "text", x: 190, y: 235, text: "lumière blanche" }),
      o("red-label", { kind: "text", x: 780, y: 208, text: "rouge" }),
      o("orange-label", { kind: "text", x: 780, y: 243, text: "orange" }),
      o("blue-label", { kind: "text", x: 780, y: 303, text: "bleu" }),
      o("violet-label", { kind: "text", x: 780, y: 338, text: "violet" }),
    ],
  },
  {
    id: "thin-lens",
    title: "Construction d’image",
    category: "Optique",
    description: "Axe optique, lentille convergente, objet et deux rayons principaux.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://tikz.net/tag/optics/",
    license: "Création originale inspirée des conventions TikZ",
    objects: [
      o("lens-axis", { kind: "line", x: 80, y: 300, x2: 820, y2: 300 }),
      o("lens", { kind: "lens", x: 450, y: 170, x2: 450, y2: 430 }),
      o("object", { kind: "arrow", x: 230, y: 300, x2: 230, y2: 175, style: concours(3) }),
      o("parallel", { kind: "light-ray", x: 230, y: 175, x2: 450, y2: 175, style: concours() }),
      o("refracted", { kind: "light-ray", x: 450, y: 175, x2: 700, y2: 385, style: concours() }),
      o("central", { kind: "light-ray", x: 230, y: 175, x2: 700, y2: 385, style: concours() }),
      o("image", { kind: "arrow", x: 700, y: 300, x2: 700, y2: 385, style: concours(3) }),
      o("f-left", { kind: "point", x: 325, y: 291, width: 18, height: 18 }),
      o("f-left-label", { kind: "text", x: 334, y: 330, text: "F" }),
      o("f-right", { kind: "point", x: 565, y: 291, width: 18, height: 18 }),
      o("f-right-label", { kind: "text", x: 574, y: 330, text: "F′" }),
    ],
  },
  {
    id: "clapeyron-gas-transformations",
    title: "Diagramme de Clapeyron — transformations d’un gaz parfait",
    category: "Thermodynamique",
    description: "Repère (P,V) de concours avec réseau d’isothermes, états repérés, transformations usuelles orientées et aire algébrique du travail des forces de pression.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/64/8/spe779_annexe_1373648.pdf",
    license: "Original creation — STEM thermodynamics conventions",
    objects: [
      o("clapeyron-frame", { kind: "thermo-diagram", x: 120, y: 120, width: 420, height: 280, annotations: { diagramType: "P-V", title: "Diagramme de Clapeyron — gaz parfait", xMin: "0", xMax: "10", yMin: "0", yMax: "10", xUnit: "m^3", yUnit: "Pa" }, style: concours(1.5) }),
      o("clapeyron-isotherms", { kind: "thermo-isotherm-family", x: 120, y: 120, width: 420, height: 280, annotations: { count: "4", main: "T_1 < T_2 < T_3 < T_4" }, style: concours(1.1) }),
      o("clapeyron-work", { kind: "pressure-work-area", x: 120, y: 120, width: 420, height: 280, annotations: { areaType: "travail fourni", main: "W_{A\\to B}=-\\int_A^B P\\,\\mathrm{d}V" }, style: concours(1.2) }),
      o("clapeyron-state-a", { kind: "thermo-state", x: 225, y: 305, width: 50, height: 50, annotations: { main: "A", pressure: "P_A", volume: "V_A", temperature: "T_A", showCoordinates: "non" }, style: concours() }),
      o("clapeyron-state-b", { kind: "thermo-state", x: 405, y: 305, width: 50, height: 50, annotations: { main: "B", pressure: "P_B", volume: "V_B", temperature: "T_B", showCoordinates: "non" }, style: concours() }),
      o("clapeyron-state-c", { kind: "thermo-state", x: 405, y: 190, width: 50, height: 50, annotations: { main: "C", pressure: "P_C", volume: "V_C", temperature: "T_C", showCoordinates: "non" }, style: concours() }),
      o("clapeyron-state-d", { kind: "thermo-state", x: 225, y: 165, width: 50, height: 50, annotations: { main: "D", pressure: "P_D", volume: "V_D", temperature: "T_D", showCoordinates: "non" }, style: concours() }),
      o("clapeyron-isobar", { kind: "thermo-process", x: 250, y: 330, x2: 430, y2: 330, annotations: { processType: "isobare", direction: "directe", main: "P=\\mathrm{cste}", exponent: "1.4", heat: "Q>0", work: "W<0" }, style: concours(2) }),
      o("clapeyron-isochor", { kind: "thermo-process", x: 430, y: 330, x2: 430, y2: 215, annotations: { processType: "isochore", direction: "directe", main: "V=\\mathrm{cste}", exponent: "1.4", heat: "Q>0", work: "W=0" }, style: concours(2) }),
      o("clapeyron-isotherm", { kind: "thermo-process", x: 430, y: 215, x2: 250, y2: 190, annotations: { processType: "isotherme", direction: "directe", main: "T=\\mathrm{cste}", exponent: "1", heat: "", work: "" }, style: concours(2) }),
      o("clapeyron-adiabat", { kind: "thermo-process", x: 250, y: 190, x2: 250, y2: 330, annotations: { processType: "adiabatique", direction: "directe", main: "PV^{\\gamma}=\\mathrm{cste}", exponent: "1.4", heat: "Q=0", work: "" }, style: concours(2) }),
    ],
  },
  {
    id: "pure-substance-phase-diagram",
    title: "Corps pur — diagramme de phases (P,T)",
    category: "Thermodynamique",
    description: "Domaines solide, liquide et vapeur séparés par les courbes d’équilibre, avec point triple, point critique et pente de fusion réglable.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/64/8/spe779_annexe_1373648.pdf",
    license: "Original creation — STEM thermodynamics conventions",
    objects: [
      o("phase-pt-water", { kind: "phase-diagram-pt", x: 120, y: 120, width: 420, height: 280, annotations: { title: "Diagramme de phases (P,T)", substance: "eau", fusionSlope: "négative" }, style: concours(1.7) }),
    ],
  },
  {
    id: "liquid-vapour-equilibrium-dome",
    title: "Équilibre liquide-vapeur — dôme de saturation",
    category: "Thermodynamique",
    description: "Dôme liquide-vapeur sur un diagramme (P,v), point critique, états de saturation et isotitres x pour lire la composition d’un mélange diphasé.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/64/8/spe779_annexe_1373648.pdf",
    license: "Original creation — STEM thermodynamics conventions",
    objects: [
      o("dome-main", { kind: "liquid-vapour-dome", x: 120, y: 120, width: 420, height: 280, annotations: { title: "Équilibre liquide-vapeur dans (P,v)", criticalPoint: "C" }, style: concours(1.8) }),
      o("dome-quality-20", { kind: "vapour-quality-line", x: 120, y: 120, width: 420, height: 280, annotations: { quality: "0.2", main: "x=0{,}2" }, style: concours(1.1, "dashed") }),
      o("dome-quality-50", { kind: "vapour-quality-line", x: 120, y: 120, width: 420, height: 280, annotations: { quality: "0.5", main: "x=0{,}5" }, style: concours(1.1, "dashed") }),
      o("dome-quality-80", { kind: "vapour-quality-line", x: 120, y: 120, width: 420, height: 280, annotations: { quality: "0.8", main: "x=0{,}8" }, style: concours(1.1, "dashed") }),
      o("dome-state-liquid", { kind: "thermo-state", x: 205, y: 310, width: 50, height: 50, annotations: { main: "L", pressure: "P_{\\mathrm{sat}}", volume: "v_\\ell", temperature: "T_{\\mathrm{sat}}", showCoordinates: "non" }, style: concours() }),
      o("dome-state-mixture", { kind: "thermo-state", x: 325, y: 270, width: 50, height: 50, annotations: { main: "M", pressure: "P_{\\mathrm{sat}}", volume: "v", temperature: "T_{\\mathrm{sat}}", showCoordinates: "non" }, style: concours() }),
      o("dome-state-vapour", { kind: "thermo-state", x: 445, y: 310, width: 50, height: 50, annotations: { main: "V", pressure: "P_{\\mathrm{sat}}", volume: "v_v", temperature: "T_{\\mathrm{sat}}", showCoordinates: "non" }, style: concours() }),
    ],
  },
  {
    id: "carnot-cycle-clapeyron",
    title: "Cycle de Carnot moteur — diagramme de Clapeyron",
    category: "Thermodynamique",
    description: "Cycle réversible orienté composé de deux isothermes et de deux adiabatiques, avec quatre états et aire représentative du travail net fourni.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://cache.media.education.gouv.fr/file/SPE1-MEN-MESRI-4-2-2021/64/8/spe779_annexe_1373648.pdf",
    license: "Original creation — STEM thermodynamics conventions",
    objects: [
      o("carnot-frame", { kind: "thermo-diagram", x: 120, y: 120, width: 420, height: 280, annotations: { diagramType: "P-V", title: "Cycle de Carnot moteur", xMin: "0", xMax: "10", yMin: "0", yMax: "10", xUnit: "m^3", yUnit: "Pa" }, style: concours(1.5) }),
      o("carnot-work", { kind: "pressure-work-area", x: 120, y: 120, width: 420, height: 280, annotations: { areaType: "travail fourni", main: "W_{\\mathrm{cycle}}<0" }, style: concours(1.1) }),
      o("carnot-cycle", { kind: "thermo-cycle", x: 120, y: 120, width: 420, height: 280, annotations: { cycleType: "Carnot", direction: "moteur", main: "1\\to2\\to3\\to4\\to1" }, style: concours(2.1) }),
      o("carnot-state-1", { kind: "thermo-state", x: 246, y: 289, width: 50, height: 50, annotations: { main: "1", pressure: "P_1", volume: "V_1", temperature: "T_f", showCoordinates: "non" }, style: concours() }),
      o("carnot-state-2", { kind: "thermo-state", x: 280, y: 193, width: 50, height: 50, annotations: { main: "2", pressure: "P_2", volume: "V_2", temperature: "T_c", showCoordinates: "non" }, style: concours() }),
      o("carnot-state-3", { kind: "thermo-state", x: 393, y: 177, width: 50, height: 50, annotations: { main: "3", pressure: "P_3", volume: "V_3", temperature: "T_c", showCoordinates: "non" }, style: concours() }),
      o("carnot-state-4", { kind: "thermo-state", x: 428, y: 273, width: 50, height: 50, annotations: { main: "4", pressure: "P_4", volume: "V_4", temperature: "T_f", showCoordinates: "non" }, style: concours() }),
    ],
  },
  {
    id: "heat-engine",
    title: "Machine thermique",
    category: "Thermodynamique",
    description: "Sources chaude et froide, machine, chaleur et travail.",
    sourceName: "Janosh Diagrams",
    sourceUrl: "https://diagrams.janosh.dev/",
    license: "Création originale à partir de concepts MIT",
    objects: [
      o("hot", { kind: "thermal-reservoir", x: 390, y: 70, width: 120, height: 90, annotations: { main: "Tₕ" } }),
      o("engine", { kind: "heat-engine", x: 375, y: 235, width: 150, height: 120, annotations: { main: "machine", hot: "Qₕ", cold: "Q𝚌", work: "W" } }),
      o("cold", { kind: "thermal-reservoir", x: 390, y: 420, width: 120, height: 90, annotations: { main: "T𝚌" } }),
      o("qh", { kind: "heat-arrow", x: 450, y: 160, x2: 450, y2: 235, annotations: { main: "Qₕ" }, style: concours(3) }),
      o("qc", { kind: "heat-arrow", x: 450, y: 355, x2: 450, y2: 420, annotations: { main: "Q𝚌" }, style: concours(3) }),
      o("work", { kind: "work-arrow", x: 525, y: 295, x2: 700, y2: 295, annotations: { main: "W" }, style: concours(3) }),
    ],
  },
  {
    id: "titration",
    title: "Dosage par titrage",
    category: "Chimie",
    description: "Burette, bécher, agitateur et support pour un montage de dosage.",
    sourceName: "Sketch2LaTeX",
    sourceUrl: "https://tikz.net/tag/chemistry/",
    license: "Création originale inspirée des conventions TikZ",
    objects: [
      o("stand", { kind: "support-stand", x: 220, y: 80, width: 170, height: 350 }),
      o("burette", { kind: "burette", x: 360, y: 85, width: 50, height: 270 }),
      o("beaker", { kind: "beaker", x: 360, y: 365, width: 135, height: 140 }),
      o("stirrer", { kind: "magnetic-stirrer", x: 340, y: 455, width: 175, height: 90 }),
      o("drop", { kind: "dashed-line", x: 385, y: 355, x2: 410, y2: 390, style: concours() }),
      o("titrant", { kind: "text", x: 470, y: 180, text: "solution titrante" }),
      o("analyte", { kind: "text", x: 565, y: 430, text: "solution à doser" }),
    ],
  },
  {
    id: "electrochemical-cell",
    title: "Pile électrochimique",
    category: "Chimie",
    description: "Deux demi-piles, pont salin et circuit extérieur.",
    sourceName: "Janosh Diagrams",
    sourceUrl: "https://diagrams.janosh.dev/",
    license: "Création originale à partir de concepts MIT",
    objects: [
      o("cell", { kind: "electrochemical-cell", x: 230, y: 190, width: 440, height: 280, annotations: { anode: "Zn (−)", cathode: "Cu (+)", bridge: "pont salin" } }),
      o("wire-left", { kind: "wire", x: 340, y: 225, x2: 340, y2: 100 }),
      o("wire-top", { kind: "wire", x: 340, y: 100, x2: 560, y2: 100 }),
      o("wire-right", { kind: "wire", x: 560, y: 100, x2: 560, y2: 225 }),
      o("current", { kind: "arrow", x: 390, y: 75, x2: 510, y2: 75, style: concours() }),
      o("current-label", { kind: "text", x: 450, y: 55, text: "e⁻" }),
    ],
  },
  {
    id: "multi-graph",
    title: "Comparaison de fonctions",
    category: "Mathématiques",
    description: "Repère avec plusieurs courbes, domaine, axes et légendes modifiables.",
    sourceName: "TikZ.net",
    sourceUrl: "https://tikz.net/data/",
    license: "Adapté sous CC BY-SA 4.0",
    objects: [
      o("graph", { kind: "axes", x: 170, y: 90, width: 560, height: 390, graph: { expression: "sin(x)", expressions: ["sin(x)", "cos(x)", "0.25*x^2-1"], xMin: -6, xMax: 6, yMin: -3, yMax: 3, xLabel: "x", yLabel: "y", showGrid: true } }),
      o("legend", { kind: "text", x: 670, y: 125, text: "sin(x), cos(x), 0.25x²−1" }),
    ],
  },
];

export const cloneTemplateObjects = (template: DiagramTemplate) => {
  const suffix = Math.random().toString(36).slice(2, 7);
  const ids = new Map(template.objects.map((object) => [object.id, `${object.id}-${suffix}`]));
  const groups = new Map(template.objects.flatMap((object) => object.groupId ? [[object.groupId, `${object.groupId}-${suffix}`] as const] : []));
  return template.objects.map((object) => ({
    ...object,
    id: ids.get(object.id)!,
    groupId: object.groupId ? groups.get(object.groupId) : undefined,
    bindings: object.bindings ? { startId: ids.get(object.bindings.startId ?? ""), startPort: object.bindings.startPort, startRatio: object.bindings.startRatio, endId: ids.get(object.bindings.endId ?? ""), endPort: object.bindings.endPort, endRatio: object.bindings.endRatio } : undefined,
    style: object.style ? { ...object.style } : undefined,
    graph: object.graph ? { ...object.graph, expressions: object.graph.expressions ? [...object.graph.expressions] : undefined } : undefined,
    annotations: object.annotations ? { ...object.annotations } : undefined,
    points: object.points?.map((point) => ({ ...point })),
    control: object.control ? { ...object.control } : undefined,
  }));
};
